export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 50,
  MAX_LIMIT: 100,
} as const;

export const RATE_LIMITS = {
  WRITES_PER_MINUTE: 60,
  API_REQUESTS_PER_SECOND: 10,
} as const;

export const FINANCIAL_THRESHOLDS = {
  HIGH_INTEREST_DEBT_APR: 8,
  EMERGENCY_FUND_MONTHS_TIER_1: 3,
  EMERGENCY_FUND_MONTHS_TIER_2: 6,
  SAVINGS_RATE_TARGET: 0.20,
  DTI_MAX_RATIO: 0.36,
  DTI_CRITICAL_RATIO: 0.50,
  BUDGET_ALERT_PERCENT: 80,
  BUDGET_CRITICAL_PERCENT: 100,
  BUDGET_OVER_MAX_PERCENT: 120,
  NET_WORTH_FLAT_THRESHOLD: -0.05,
  IRA_ANNUAL_LIMIT: 7000,
} as const;

export const FHS_WEIGHTS = {
  SAVINGS_RATE_MAX: 30,
  DTI_MAX: 25,
  EMERGENCY_FUND_MAX: 20,
  BUDGET_ADHERENCE_MAX: 15,
  NET_WORTH_TREND_MAX: 10,
} as const;

export const DEFAULT_CURRENCY = 'USD';
export const DEFAULT_LOCALE = 'en-US';
export const JWT_EXPIRY_DAYS = 7;
