import { Link } from 'react-router-dom';
import { IconTerms } from '@/components/ui/Icons';

export function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl space-y-8 py-8">
      <div className="flex items-center gap-3">
        <IconTerms className="h-6 w-6 text-brand-600" />
        <div>
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Terms of Service</h1>
          <p className="text-sm text-slate-500 dark:text-slate-400">Last updated: July 9, 2026</p>
        </div>
      </div>

      <section className="space-y-4 text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
        <h2 className="text-lg font-semibold text-slate-900 dark:text-white">1. Acceptance of Terms</h2>
        <p>By creating a BudgetOS account, you agree to these Terms of Service. If you do not agree, do not use the service. We reserve the right to update these terms; continued use after changes constitutes acceptance.</p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-white">2. Description of Service</h2>
        <p>BudgetOS is an AI-powered personal finance management application. We provide budgeting tools, financial tracking, AI-powered insights, report generation, and data export. The service is available in Free, Pro, and Premium tiers as described on our Pricing page.</p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-white">3. User Responsibilities</h2>
        <p>You are responsible for maintaining the confidentiality of your account credentials. You agree not to use BudgetOS for any illegal purpose, to not attempt to reverse-engineer the service, and to not interfere with other users' access.</p>
        <p>You represent that all information you provide is accurate and current. You are solely responsible for the accuracy of your financial data.</p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-white">4. Billing & Subscriptions</h2>
        <p>Paid plans (Pro, Premium) are billed monthly or annually as selected at checkout. Payments are processed securely by Stripe. Subscriptions auto-renew unless canceled at least 24 hours before the renewal date. Refunds are provided within 14 days of initial purchase on a case-by-case basis.</p>
        <p>Downgrading to Free takes effect at the end of the current billing period. No partial refunds are provided for unused portions of a billing period.</p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-white">5. Data Ownership</h2>
        <p>You retain full ownership of your financial data. BudgetOS claims no intellectual property rights over your data. We may use anonymized, aggregated data for analytics and service improvement.</p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-white">6. AI Services</h2>
        <p>AI Copilot responses are generated by OpenAI's language models and may not always be accurate. You should independently verify important financial decisions. BudgetOS is not liable for decisions made based on AI-generated recommendations. AI usage is subject to rate limits based on your subscription tier.</p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-white">7. Limitation of Liability</h2>
        <p>BudgetOS is provided "as is" without warranty of any kind. We are not liable for any damages arising from use of the service, including but not limited to data loss, financial loss, or service interruption. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.</p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-white">8. Termination</h2>
        <p>You may terminate your account at any time from Settings. We may suspend or terminate accounts for violation of these terms. Upon termination, your data will be permanently deleted within 30 days.</p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-white">9. Governing Law</h2>
        <p>These terms are governed by the laws of the State of Delaware, United States. Any disputes shall be resolved in the courts of Delaware.</p>
      </section>

      <div className="border-t border-slate-200 pt-6 dark:border-slate-800">
        <Link to="/auth/signup" className="text-sm text-brand-600 hover:text-brand-500 dark:text-brand-400">
          &larr; Back to Sign Up
        </Link>
      </div>
    </div>
  );
}
